### ISSUE TITLE
Do not install Go (or any tool you reference in a login shell script) into /tmp

### ISSUE THREAD

**Issue by viktorbenei** [szamcsi/golang-elte-2019-public#2]
https://github.com/szamcsi/golang-elte-2019-public/blob/0133a0cb396d87f6ad15e28943556632fe2e6936/script/install_go.sh#L45

Files & dirs under `/tmp` are deleted when you reboot the computer, but the `~/.bashrc` / `~/. zshrc` will still point to it.

Is there a reason you don't want to install go to the officially suggested location, `/usr/local/go`? https://golang.org/doc/install

**Comment by szamcsi** [comment]
Yes: lack of permissions on the centrally managed machine.
